修改配方，更新多方块、本地化
mcstaralliance/Scripts pull request #197
Opened 2023-06-26 15:40 UTC by Dabai1025

2023-06-26 15:53 UTC, LDS-XiaoYe requested changes

2023-06-26 15:53 UTC, LDS-XiaoYe commented on scripts/modtweaker/astralsorcery.zs
> +	<astralsorcery:blockmarble:6>, <astralsorcery:itemrockcrystalsimple>, <astralsorcery:blockmarble:6>]
请不要使用制表符。

2023-06-26 15:53 UTC, LDS-XiaoYe commented on resources/contenttweaker/lang/zh_cn.lang
> +multiblocked.recipe_map.08395aa0-337b-420a-9ea1-c8eb2d4d381b=\u661f\u529b\u7ec4\u88c5\u914d\u65b9
命名不规范

2023-06-26 15:53 UTC, LDS-XiaoYe commented on scripts/utils.zs
> +
应移动到 `recipes.zs`

2023-06-27 17:33 UTC, Dabai1025 commented
再打回就不写了

2023-06-27 17:40 UTC, LDS-XiaoYe approved these changes

2023-06-27 17:41 UTC, merged